{{ if .Values.keyVault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "default-app.fullname" . }}-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.keyVault.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "default-app.fullname" . }}-secret
  data:
{{- range .Values.keyVault.secrets }}
  - secretKey: {{ .name }}
    remoteRef:
      key: {{ .key }}
{{- end }}
{{ end }}
