{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "default-app.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "default-app.name" . }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    path: {{ .Values.serviceMonitor.path }}
{{ end }}
