name: Package and Push Helm Chart to ACR

on:
  push:
    branches:
      - main
    paths:
      - 'hcn-helm-charts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'hcn-helm-charts/**'

env:
  REGISTRY: youracr.azurecr.io
  CHART_PATH: hcn-helm-charts
  CHART_NAME: hcn-helm-charts

jobs:
  package-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Helm
      run: |
        curl https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz -o helm.tar.gz
        tar -zxvf helm.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin/helm

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | helm registry login ${{ env.REGISTRY }} --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Package Helm chart
      run: |
        cd ${{ env.CHART_PATH }}
        helm package .

    - name: Push Helm chart to ACR
      run: |
        helm push ${{ env.CHART_NAME }}-*.tgz oci://${{ env.REGISTRY }}/helm/